### ISSUE TITLE
api down

### ISSUE THREAD

**Issue by blaaaaaaa** [MicroPyramid/forex-python#86]
api down for me

**Comment by adiabuk** [comment]
looks like they've changed the DNS name

**Comment by adiabuk** [comment]
Not sure if this repo is still maintained, but I created a pull request with a working API URL: https://github.com/MicroPyramid/forex-python/pull/87

**Comment by fredzannarbor** [comment]
api down for me too

**Comment by asafravid** [comment]
+1, I reverted to using manual updates of Forex rates
Do you guys know of another automation library present...?

**Comment by wkulikowski** [comment]
I'm switching to [CurrencyConverter](https://pypi.org/project/CurrencyConverter/) if anybody is interested. Used for one project, worked fine.

**Comment by adiabuk** [comment]
@asafravid - try applying my fix above.  I've committed that to my fork as not sure if the PR will be approved here.  https://github.com/adiabuk/forex-python/  It works as before

**Comment by pyFrappe** [comment]
> @asafravid - try applying my fix above. I've committed that to my fork as not sure if the PR will be approved here. https://github.com/adiabuk/forex-python/ It works as before

When i use your fork , i get this error:
HTTPSConnectionPool(host='exchangeratesapi.iolatest', port=443): Max retries exceeded with url: /?base=USD&rtype=fpy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection 
object at 0x000001EE029D7DC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

I tried changing return "https://exchangeratesapi.io" to return "https://exchangeratesapi.io/" but then it shows:
Currency Rates Source Not Ready

Do you have any idea on what's going on , i was using this module on a production server and now nothing seems to be working and i am getting tons of mails.

**Comment by konrad-ixium** [comment]
@pyFrappe
As I have commented on @asafravid fix, I managed to get a response when I changed the url to "https://api.exchangeratesapi.io/api/", however when you dig deeper you only receive a response that states you need an API access key, I don't think this service will continue operating the same way. I think the best option is the CurrencyConverter module as mentioned above by @wkulikowski.

Just to also put it out there I have tried making an account with exchangeratesapi and I got forex_python to send the access key, however on the free account you're very limited in terms of functionality and the amount of calls you can make monthly is tiny.

**Comment by billy-doyle** [comment]
Appears need an api key as the DNS name has indeed changed and they now require an api key, with tiered pricing. https://exchangeratesapi.io/pricing/. Will also be switching to [CurrencyConverter](https://pypi.org/project/CurrencyConverter/)

**Comment by asafravid** [comment]
@pyFrappe - your fix doesn't work - see above mentions
I tried yours, there's still an error
@wkulikowski - Does CurrencyConverter work on Python 3.8+? I used it previously but had issues when moved to Python 3.8
I'll give it another go though...

**Comment by konrad-ixium** [comment]
> @pyFrappe - your fix doesn't work - see above mentions
> I tried yours, there's still an error
> @wkulikowski - Does CurrencyConverter work on Python 3.8+? I used it previously but had issues when moved to Python 3.8
> I'll give it another go though...

I'm running CurrencyConverter on 3.8.1 on several repos, seems to work fine. The only thing is you need to remember to update the file that it gets the exchanges from. That almost caught me off guard, wouldn't want to find out months later the rates were not changing haha

**Comment by adiabuk** [comment]
I'll probably move to CurrencyConverter too once I get a chance.  For now, luckily I had the IP cached so I just put the following into /etc/hosts: `104.21.66.222 api.ratesapi.io`  
I'm expecting that to stop working soon though

**Comment by DongHyeokKim** [comment]
> I'll probably move to CurrencyConverter too once I get a chance. For now, luckily I had the IP cached so I just put the following into /etc/hosts: `104.21.66.222 api.ratesapi.io`
> I'm expecting that to stop working soon though

your code doesn't work.. ㅠ_ㅠ

**Comment by asafravid** [comment]
> @asafravid
> 
> > @pyFrappe - your fix doesn't work - see above mentions
> > I tried yours, there's still an error
> > @wkulikowski - Does CurrencyConverter work on Python 3.8+? I used it previously but had issues when moved to Python 3.8
> > I'll give it another go though...
> 
> I'm running CurrencyConverter on 3.8.1 on several repos, seems to work fine. The only thing is you need to remember to update the file that it gets the exchanges from. That almost caught me off guard, wouldn't want to find out months later the rates were not changing haha

Great, thankd @konrad-ixium

**Comment by asafravid** [comment]
This one is creat too (I guess it is the CurrencyConverter library mentioned?)

```
from bs4 import BeautifulSoup
import PyCurrency_Converter
```

**Comment by DaBors** [comment]
If someone just wants to hotfix their code this PR should solve the issue https://github.com/MicroPyramid/forex-python/pull/88
You need to provide your access_key as an argument to CurrencyRates

You can get the free and limited access_key here https://manage.exchangeratesapi.io/signup/free

On the pricing page they say it's 250 Request per month, but once you create an account it actually shows 1000 request per month.

**Comment by asafravid** [comment]
So, it goes like this:

from currency_converter import CurrencyConverter
currency_conversion_tool_alternative = CurrencyConverter()
conversion_rate_mult_to_usd = round(currency_conversion_tool_alternative.convert(1.0, financial_currency, 'USD'), NUM_ROUND_DECIMALS)

**Comment by DongHyeokKim** [comment]
> So, it goes like this (Example):
> 
> ```
> from currency_converter import CurrencyConverter
> currency_conversion_tool_alternative = CurrencyConverter()
> conversion_rate_mult_to_usd = round(currency_conversion_tool_alternative.convert(1.0, financial_currency, 'USD'), NUM_ROUND_DECIMALS) 
> ```

I couldn't get latest data from this library.. so I made code myself as below

`from io import BytesIO
from zipfile import ZipFile
from urllib.request import urlopen


ECB_URL = 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.zip'
res = urlopen(ECB_URL)
zipfile = ZipFile(BytesIO(res.read()))
line_list = zipfile.open('eurofxref-hist.csv').readlines()

latest_14th_list = [sub.decode('utf-8').split(',') for sub in line_list[:15]]
df_ex_rate = pd.DataFrame(latest_14th_list[1:], columns=[latest_14th_list[0]])`

However, there is no data for the weekend in this data. When using forex-python, how was the exchange rate for the weekend defined?

**Comment by billy-doyle** [comment]
I was using forex-python to just pull the available currency rates to USD once per day. The following code with the https://exchangeratesapi.io/ api yields the USD currency rates for all the available currencies by day, if anyone else needs.

```python
def get_rates(date):
    
    url = f'http://api.exchangeratesapi.io/v1/{date}'
    params = {
        'access_key': os.environ['EXCHANGE_RATE_KEY']
    }
    
    r = requests.get(url, params=params)
    
    if not r.ok:
        r.raise_for_status()
    
    data = r.json()
    
    rates = data.get('rates')
    BASE = data.get('base')
    
    USD = rates['USD']
    curr_to_dollar = rates[BASE] / USD

    us_rates = {}
    for k, v in rates.items():
        if k == 'USD':
            us_rates[k] = 1
        else:
            us_rates[k] = curr_to_dollar*v
        
    df = pd.io.json.json_normalize(us_rates).T.reset_index()
    df['date'] = pd.Timestamp(date)
    df.columns = ['currency', 'rate', 'date']
    
    return df[['date', 'currency', 'rate']]
```

**Comment by youyanggu** [comment]
Here's my replacement function that uses the https://exchangeratesapi.io/ API. It's similar to @billy-doyle's but directly returns the exchange rate given a currency pair and date:

```python
def get_exch_rate(cur, base_cur='USD', date=None):
    assert len(cur) == 3, f'Not valid currency: {cur}'
    assert len(base_cur) == 3, f'Not valid base currency: {base_cur}'

    if date is None:
        date_str = 'latest'
    else:
        date_str = str(date)

    cur_with_base = f'{cur},{base_cur}'

    url = f'http://api.exchangeratesapi.io/v1/{date_str}'

    params = {
        'access_key' : os.environ['EXCHANGE_RATE_KEY'],
        'symbols' : cur_with_base,
    }

    resp = requests.get(url, params=params)
    if not resp.ok:
        resp.raise_for_status()

    data = resp.json()
    rates = data['rates']

    rate = rates[cur] / rates[base_cur]

    return rate
```

**Comment by youyanggu** [comment]
Here's my replacement function that uses the https://exchangeratesapi.io/ API (you can create a free account and get the API key for 1000 requests/month). It's similar to @billy-doyle's but directly returns the exchange rate given a currency pair and date (if no date, returns latest rate):

```python
def get_exch_rate(cur, base_cur='USD', date=None):
    assert len(cur) == 3, f'Not valid currency: {cur}'
    assert len(base_cur) == 3, f'Not valid base currency: {base_cur}'

    date_str = 'latest' if date is None else str(date)
    url = f'http://api.exchangeratesapi.io/v1/{date_str}'
    params = {
        'access_key' : <ACCESS_KEY>,
        'symbols' : f'{cur},{base_cur}',
    }

    resp = requests.get(url, params=params)
    if not resp.ok:
        resp.raise_for_status()

    data = resp.json()
    rates = data['rates']

    rate = rates[cur] / rates[base_cur]

    return rate
```

**Comment by nandesh553** [comment]
Switched to [currencyconverter](https://github.com/alexprengere/currencyconverter)

**Comment by ashwin31** [comment]
@all API working now
